name: Terraform Plan on PR

on:
  workflow_dispatch:
    inputs:
      tf_directory:
        description: 'Terraform directory (e.g. envs/dev)'
        required: true
        default: 'envs/dev'

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan on PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.9

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.event.inputs.tf_directory }}
      #working-directory: environments/dev


    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ github.event.inputs.tf_directory }}
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
