name: Terraform Apply on Merge to Main

on:
  workflow_dispatch:
    inputs:
      tf_directory:
        description: 'Terraform directory (e.g. infra/, terraform/dev)'
        required: true
        default: 'envs/dev'
      create:
        description: 'Destroy?'
        required: true
        default: 'false'
        type: boolean          
  push:
    
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply on Main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.event.inputs.tf_directory }}
      

    - name: Terraform Apply

      run: terraform apply -auto-approve
      working-directory: ${{ github.event.inputs.tf_directory }}
      
    - name: Terraform Destory
      if: ${{ github.event.inputs.create == 'true' }}
      run: terraform destroy -auto-approve
      working-directory: ${{ github.event.inputs.tf_directory }}        
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
